language: node_js
node_js:
- stable
script:
  - npm run lint
  - npm run cover
  - npm run coveralls
deploy:
  provider: npm
  email: pcandido.m@gmail.com
  skip_cleanup: true
  api_key:
    secure: "NfpGF9D0nn5KmxBaj3TgbUw43bfAieDMjJQwJGZ4fctvsMFp9ZblPDCPnJVIGbUwvx+mR7mPxFJDgrfpG3tKcsAew90XrkgIBa6nVwCPDu8P0XbEWxXdCOBErLt6tHDCT+DOtfOELQyAYpUn5eeHjeaio5y/huDxU2YyNV2aHBzzMeenBA1vrpgwoid7aFOMpBejmqJLDv3Nss6HOo3kRMaFfir1+hrrTpVRxWOKrRlIY2fCdSy4tJyTnAl+b0pHZgsdu2Z4EOJS6mkz4exhziiRXlPmV5cmu4f/pV8POAFqVtlTszeLVu4SVw7N3pPqJ4ge/fMVzNCYsB7NKB/+J1kjqZwS9P6D0zawVQ69O1twfuwmIwU9+QkNaz0GlrQX9Jt0Hgi1u235aJxaCUHhv1wZCKDlfHvYevuhAW6W+dh0gV70u4nA3UkyDNHvsdK6VwJfaYUO/7krl0ki8NR68OL0v3FCFDpn7LGuAploRUYJSJDHCMwI3VptCVDmYvpYctlM6e0UfpEKP7BDbM2e2QIuU5gYAePrp6IzYJ4SgGbCud4Nj0cdr+6PqEI78biIU9M5KzCrFFmtq9IbiMRaVLDg0Iy7ba0xlHnR8iPhXKR+zYH7YDH2VS+o1N4FGLSQQnIAnnIpd6+ivjYvogDFcqPDL3XFGGLeM+KJ5L7F1HI="
