language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g codecov
  - npm install -g blanket
script:
  - NODE_ENV=test SPARRAY_COVERAGE=1 ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter
  - codecov
